StockManagement.Web/Components/SalesLineChartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.Application.Interfaces;
using StockManagement.Web.Models;

namespace StockManagement.Web.Components
{
    [ViewComponent]
    public class SalesLineChartViewComponent(IOrderService _orderService): ViewComponent
    {
        public IViewComponentResult Invoke(int days)
        {
            var model = _orderService.GetTotalSalesByDateLastNDays(days)
                .Select(d => new DateStatsViewModel(d));
            return View(model);
        }
    }
}

StockManagement.Web/Components/StockColumnChartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StockManagement.Application.Interfaces;
using StockManagement.Web.Models;

namespace StockManagement.Web.Components
{
    [ViewComponent]
    public class StockColumnChartViewComponent(IProductService _productService) : ViewComponent
    {
        public IViewComponentResult Invoke(int days)
        {
            var products = _productService.GetStockOfNMostSoldProductsLastNDays(10, days)
                .Select(p => new ProductStockViewModel(p));
            return View(products);
        }
    }
}

StockManagement.Web/Controllers/DashboardController.cs
using IronPdf;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using StockManagement.Web.Guards;

namespace StockManagement.Web.Controllers
{
    public class DashboardController: Controller
    {
        [Authorize(Roles = "Admin")]
        public IActionResult Index([FromQuery] int days = 30)
        {
            ViewBag.days = days;
            return View();
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Print([FromQuery] int days = 30)
        
        {
            ViewBag.days = days;
            return File(new ChromePdfRenderer().RenderUrlAsPdf(Url.Action(
                action: "PdfTemplate",
                controller: "Dashboard",
                values: new { days },
                protocol: Request.Scheme
            )).BinaryData, "application/pdf");
        }

        [LocalOnly]
        public IActionResult PdfTemplate([FromQuery] int days = 30)
        {
            ViewBag.days = days;
            return View();
        }
    }
}

StockManagement.Web/Views/Dashboard/Index.cshtml
@{
    ViewBag.Title = "Dashboard";
    int[] days = [10, 30, 50, 100];
}

<div class="container-fluid">
    <div class="row mb-3">
        <div class="col-6 col-lg-9">
            <a class="btn btn-primary" asp-action="Print"><i class="fa fa-print"></i></a>
        </div>
        <div class="col-6 col-lg-3">
            <form method="get" class="d-flex gap-2">
                <select name="days" class="form-select">
                    @foreach(int d in days)
                    {
                        @if(d == ViewBag.Days) { <option selected value="@d">@d derniers jours</option> }
                        else{ <option value="@d">@d jours</option> }
                    }
                </select>
                <button class="btn btn-primary">Modifier</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12 col-lg-6">
            <vc:stock-column-chart days="ViewBag.Days"></vc:stock-column-chart>
        </div>
        <div class="col-12 col-lg-6">
            <vc:sales-line-chart days="ViewBag.Days"></vc:sales-line-chart>
        </div>
    </div>
</div>



@section Scripts {
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
}

StockManagement.Web/Views/Dashboard/PdfTemplate.cshtml
@{
    Layout = null;
}

<div class="container-fluid">
    <div class="row">
        <div class="col-12 col-lg-6">
            <vc:stock-column-chart days="ViewBag.Days"></vc:stock-column-chart>
        </div>
        <div class="col-12 col-lg-6">
            <vc:sales-line-chart days="ViewBag.Days"></vc:sales-line-chart>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>